### ISSUE TITLE
Add download command example in the README

### ISSUE THREAD

**Issue by haa-gg** [LifeEGX/methylprep#44]
Could you include an example of what the download command would look like in the README?

**Comment by marcmaxson** [comment]
Sure, here:
https://life-epigenetics-methylprep.readthedocs-hosted.com/en/latest/docs/cli.html#download

In full verbose mode, it would be:

```
python -m methylprep -v download -i GSE69852 -d .
python -m methylprep -v process -d . --betas
```
that will create CSVs for each sample off the current folder, and return a betas.pkl file with all betas for samples in one file.
